Repository burningmantech/ranger-ims-server, pull requests merged in 2024-02, with the labels that each got.

#1100 Let pre-commit automerge. Disable Safety.
  .github/workflows/automerge.yml
  .github/workflows/cicd.yml
Labels: Task

#1088 feat: help user not lose unsaved changes
  src/ims/element/static/incident.js
  src/ims/element/static/incident_report.js
Labels: Enhancement

#1101 Update Klein
  .isort.cfg
  requirements/requirements-direct.txt
  src/ims/application/_api.py
  src/ims/application/_auth.py
  src/ims/application/_klein.py
  src/ims/application/_main.py
  src/ims/application/_web.py
  src/ims/element/_element.py
  src/ims/element/page/_page.py
  src/ims/ext/test/test_klein.py
Labels: Task

#1026 Switch to Python 3.12
  .github/workflows/cicd.yml
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
  Dockerfile
  pyproject.toml
  setup.py
  tox.ini
Labels: Task

#1102 Werkzeug 3.0.1
  requirements/requirements-direct.txt
  src/ims/application/_klein.py
Labels: Task

#1112 Add cli.codecov.io to HR
  .github/workflows/cicd.yml
  .github/workflows/deploy.yml
Labels: Task

#1119 Back to audit mode
  .github/workflows/deploy.yml
Labels: Show Stopper, Task

#1120 Fix harden config
  .github/workflows/deploy.yml
Labels: Task
